# Generated by Django 2.2.10 on 2021-02-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item1_todolist1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item1',
            name='todolist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ToDoList1'),
        ),
    ]
