# Generated by Django 2.2.10 on 2021-02-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210205_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item1',
            name='todolist',
        ),
        migrations.RemoveField(
            model_name='item2',
            name='todolist',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Item1',
        ),
        migrations.DeleteModel(
            name='Item2',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
        migrations.DeleteModel(
            name='ToDoList1',
        ),
        migrations.DeleteModel(
            name='ToDoList2',
        ),
    ]
