# Generated by Django 2.2.10 on 2021-02-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
